spring:
  application:
    name: course-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/courseservice_db?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: Decembrie2001

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  jwt:
    secretKey: asdasdasdasdasd123344asdasdasdasdasasd12321332sadas
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 7

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8082

feign:
  client:
    config:
      default:
        loggerLevel: full
        
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

param:
  courses-auth-service: localhost

metrics:
  distribution:
    percentiles-histogram:
      http:
        server:
          request: true
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health, info, prometheus
    endpoint:
      prometheus:
        enabled: true

  logging:
    pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
    level:
      root: debug
    file:
      name: test.log

logs:
  destination: localhost:3100