spring:

  datasource:
    url: jdbc:mysql://mysql:3306/courseservice_db?createDatabaseIfNotExist=true
    username: root
    password: root

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

param:
  courses-auth-service: courses-auth-service

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans


logs:
  destination: logstash:3100